### ISSUE TITLE
Not able to find personal feed URL

### ISSUE THREAD

**Issue by crunchtime-ali** [plibither8/github-feed-notifier#1]
I have been looking up and down the old and new dashboard but could not find a link to my personal feed URL. I could only find it for organizations (see screenshot below).

Is there another way to retrieve that URL?

![image](https://user-images.githubusercontent.com/7140800/44794756-6f4dea00-aba9-11e8-8214-c6166d691ce4.png)

**Comment by plibither8** [comment]
Hmm, that's unfortunate. I've checked through different GitHub profiles of my friends once they were logged in and they all seem to have that button. Try "Find in page" for "subscribe" when you're at your [dashboard](https://github.com/dashboard). Apart from that, I do not know of any other way to retrieve that URL. If this issue is prevalent amongst more users, I'll look deeper for a fix. Thanks!

**Comment by crunchtime-ali** [comment]
@plibither8 I used this GitHub extension which was getting rid of the feed URL link https://github.com/sindresorhus/refined-github
Maybe you should add a note to the README.md about that.

**Comment by plibither8** [comment]
Ahh, alright. I'm glad you could fix that. I'll make sure to add that note, thanks :smile:
